#spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521:ORCL
#    username: ITSOLDEMO
#    password: phamtuankiet

#     url: jdbc:oracle:thin:@localhost:1521:qlsvitsol
#     username: GIAP1234
#     password: 1234
#     url: jdbc:oracle:thin:@localhost:1521:sa
#     username: QLDT
#     password: 123
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.OracleDialect
#        format_sql: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username:  cutetiger98.java@gmail.com
#    password: vkqingjddopedqbw
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true

server:
  port: 8080

spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:sa
    username: ITSOLDEMO2
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username:  cutetiger98.java@gmail.com
    password: vkqingjddopedqbw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  active-account:
    active-url: "http://localhost:8080/active/"
